FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci || npm install

COPY . .

# Vite poort
EXPOSE 5173

# Start dev-server en luister op alle interfaces
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
